name: aplicacionlensys
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI y fuentes
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1

  # Estado y lógica
  flutter_riverpod: ^2.6.1

  # Almacenamiento y seguridad
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4

  # UUID
  uuid: ^4.5.1

  # Internet y red
  http: ^1.2.1
  internet_connection_checker: ^1.0.0+1

  # Gráficos y visualización
  fl_chart: ^0.66.0

  # Selección de archivos e imágenes
  file_picker: ^10.3.2
  image_picker: ^1.2.0
  file_selector: ^1.0.3

  # Notificaciones
  flutter_local_notifications: ^17.1.2

  # Fecha y hora
  intl: ^0.20.2
  timezone: ^0.9.2

  # Exportación de archivos
  excel: ^4.0.6
  pdf: ^3.11.3
  docx_template: ^0.4.0

  # Permisos
  permission_handler: ^12.0.1

  # Backend
  supabase_flutter: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/t1.json
    - assets/t2.json
    - assets/t3.json
    - assets/estructura.json
    - assets/logo.webp
    - assets/shingomodel.webp
